### ISSUE TITLE
Fix decreased header gap on Resources page

### ISSUE THREAD

**Issue by alex-bellon** [UTACM/TexasACM.org#100]
Have been unable to replicate on all devices, but on some the spacing between the banner and the start of the content is decreased and looks crowded. 

Old:
![screenshot from 2018-12-29 10-58-21](https://user-images.githubusercontent.com/24237402/50540523-e051de00-0b58-11e9-9230-509cdf0adf3e.png)

New:
![screenshot from 2018-12-29 10-58-50](https://user-images.githubusercontent.com/24237402/50540524-e2b43800-0b58-11e9-981f-79e9c607e6a0.png)

**Comment by alex-bellon** [comment]
Woo! Issue 100!

**Comment by rolsanmordua** [comment]
Need to determine under which conditions we see the header decrease. If you look at main.css, it has custom scaling rules for display-widths for 1680px, 1280px, 980px, 736px, 480px IIRC. I would suggest testing these display widths independently to see if you can determine when the header gap appears.

If the issue can't be reproduced, maybe we should close it?

**Comment by rolsanmordua** [comment]
Issue needs to be isolated, see comment above.

**Comment by alex-bellon** [comment]
I think we need to change the top padding for `main` from `1em` to `2em`. I need to do more testing on it though, to make sure it doesn't mess up other things.
