### ISSUE TITLE
Remove slideshow.js

### ISSUE THREAD

**Issue by ChiaHuaLu** [UTACM/TexasACM.org#119]
slideshow.js is intended to dynamic-ify the homepage slideshow photos, but we only occasionally update the slideshow, and we ran into async issues while implementing slideshow.js so we decided to cancel the project

**Comment by rolsanmordua** [comment]
In the past, slideshow has been updated for White Elephant/Mozarts, retreat, Kickoff events, and advertisements like PC. This is generally 2-3 times per semester. At most we would be updating this once per month. As a result, I am dropping slideshow.js.
