### ISSUE TITLE
ACM Sucks

### ISSUE THREAD

**Issue by michaelasper** [UTACM/TexasACM.org#128]
I think this org should be shut down for money laundering

**Comment by ChiaHuaLu** [comment]
😢

**Comment by ChiaHuaLu** [comment]
well we did buy a vacuum recently so I guess ACM sucks is a true statement

**Comment by aprilhare19** [comment]
Please direct all complaints to our official Complaints Department: hr@texasacm.org

Have a blessed day,
April
