### ISSUE TITLE
Open README for Texas ACM

### ISSUE THREAD

**Issue by rolsanmordua** [UTACM/TexasACM.org#131]
Perhaps some things to include: 
- Setup and launch instructions
- A file manifest (list of files included, generic)
- Copyright and licensing information [theme has a license]
- Contact information for the developers (webmaster@texasacm.org, dev Githubs?)
- Credits and acknowledgements (Pixelarity theme, Tabletop.js devs, etc)
- Project start date (Oct 28th, 2017 @hackTX)

Anything else that may be worth including.

**Comment by alex-bellon** [comment]
Created. Decided to move most of the heavy details to the Wiki to avoid a wall of information right when you open the repo.
