### ISSUE TITLE
[Spike] Add Google Form to make forms, and have them auto-delete

### ISSUE THREAD

**Issue by alex-bellon** [UTACM/TexasACM.org#142]
Make it simple for officers to make a Google Form and assign it a URL. Also, implement a "expiration date' when the form will automatically be removed from the website to avoid clutter.

**Comment by alex-bellon** [comment]
Infeasible based on what I've looked into (at least for now)

**Comment by ChiaHuaLu** [comment]
What you might consider doing is, on webpage Js, hide and just not show forms that are expired by a certain amount. Then, using just spreadsheet format script, make expired rows highlight a different color so it’s easier to clean up during periodic manual cleaning
