### ISSUE TITLE
Make periodic static backup of website

### ISSUE THREAD

**Issue by alex-bellon** [UTACM/TexasACM.org#157]
Make a backup of static website every day or so in case `tabletop.js` goes down.

**Comment by ChiaHuaLu** [comment]
I don't think this is necessary. Daily backing up the website has a lot of time and space costs associated with it, but it does't take much time at all to recreate the website statically by manually looking at the sheets and making the table

**Comment by ChiaHuaLu** [comment]
What we should investigate though is if there are any alternatives to a Tabletop, Google Sheets solution that would still be easy for ACM Officers to use. Maybe an actual database, api, and front end system or such.

**Comment by alex-bellon** [comment]
It is tedious, I just went through it. We don't need to keep an entire backup of every version. Just copy the resulting HTML daily so I don't have to do this again.

**Comment by ChiaHuaLu** [comment]
idk what approach you took but converting the sheets to hardcode part itself only took me like 5 minutes, debug redirects and everything else within 15 minutes

**Comment by ChiaHuaLu** [comment]
Maybe look into switching from
Tabletop->Gsheet architecture to something maybe
API Gateway->Lambda->Gsheet or
API Gateway->Lambda->Dynamo or something.
