### ISSUE TITLE
Update FAQ page URLs

### ISSUE THREAD

**Issue by rolsanmordua** [UTACM/TexasACM.org#158]
Several URLs on the FAQ page are outdated and therefore broken including membership.html which is now resources.html and events.html which is now calendar.html

**Comment by rolsanmordua** [comment]
I think bylaws should be a relative path rather than an absolute path.

**Comment by rolsanmordua** [comment]
Add Discord to "How can I get more involved with ACM?"

**Comment by alex-bellon** [comment]
Fixed both. These were changes in the Google Sheet so nothing new to commit, go ahead and merge when you want.
