### ISSUE TITLE
Replace Prog Comp slide with Recruiting Challenge

### ISSUE THREAD

**Issue by Clendenin** [UTACM/TexasACM.org#170]
Prog Comp slide in slide deck on home page needs to be replaced with "Recruiting Challenges"  slide

**Comment by alex-bellon** [comment]
I need to find the new promotional material, change the size so it fits in slideshow, and then I'll update it.

**Comment by rolsanmordua** [comment]
I can update the original image (.ai file format) if easier/quicker/desired.
