### ISSUE TITLE
Update content in FAQ

### ISSUE THREAD

**Issue by alex-bellon** [UTACM/TexasACM.org#199]
- **Become a member**: Add ACM Plus link?
- **Events ACM organizes**: We don't do PC or tutoring anymore, update to have CS101 and UDE Review

All of this is through dynamic resources so you don't really need to change the code.

**Comment by lillytian** [comment]
Do these descriptions work?
- Take your involvement in ACM one step further and become an ACM Plus member <link>here</link>!
- ACM organizes a variety of events. We have lecture series with professors, professional networking events where companies come to speak, CS101 workshops and UDE reviews, and we host social events as well!

**Comment by alex-bellon** [comment]
Beautiful :100:
