### ISSUE TITLE
Prepare Elections page

### ISSUE THREAD

**Issue by rolsanmordua** [UTACM/TexasACM.org#200]
Need to prepare page for platforms and subsequently page to access voting for digital voting this semester.

**Comment by alex-bellon** [comment]
Update `elections.html`:
- [ ] Title of the page (what goes in the tab) to 20-21
- [ ] Update main header to 20-21
- [ ] Update form link and due date
- [ ] Update elections date
- [ ] Add platforms from 19-20 to the list of old ones
- [ ] Update the link in `assets/css/elections.js` to have the new link to the google form for dynamic resources

**Comment by alex-bellon** [comment]
- [ ] Fix link to office descriptions (should point [here](https://docs.google.com/document/d/1UbS-NDvMw3lf7ULyUyYdi1esXkD4t1sX89zonE8Hc9Y/edit))
