### ISSUE TITLE
Make index.html slideshow dynamic

### ISSUE THREAD

**Issue by rolsanmordua** [UTACM/TexasACM.org#54]
Keep in mind...
- Banner should be left hardcoded to compensate for loading time of DR (should happen before first transition finishes)
- JS has to be loaded before main.js

**Comment by ChiaHuaLu** [comment]
Jquery sounds intimidating but isnt really that bad. It expands what you can do with javascript. 

With jquery, you can use $('#imgId').src='http://...'; to change an image's source. Whereas without jquery, you would do the same thing as
document.getElementById('imgId').src='http://...';

You can select all elements of a class with $('.className') and do something to it.

Jquery also lets you do things you cant do before. Look up jquery API. An example would be $('#photo').fadeIn(100); to fade in an image over 1 second

**Comment by rolsanmordua** [comment]
We don't update this part of the page enough to justify Dynamic Resource implementation.
