### ISSUE TITLE
Improve implementation of officer cards

### ISSUE THREAD

**Issue by rolsanmordua** [UTACM/TexasACM.org#83]
- Optimize for mobile in landscape view (reduce spacing between cards, make them wider, make them go to edge of page margins in line with content above, make button alignment better)
- Make cards consistent height.

**Comment by rolsanmordua** [comment]
I can give this issue a go over the summer..

**Comment by alex-bellon** [comment]
I spent a lot of time on this in the Spring when I updated the cards for new officers and have mostly fixed all the issues. Currently they fit well and are the same size.
