### ISSUE TITLE
[Spike] Investigate Google Calendar Weekly View for home page

### ISSUE THREAD

**Issue by ChiaHuaLu** [UTACM/TexasACM.org#88]
Home page's Upcoming Events is not helpful at all. Maybe find a way to put a weekview Google Calendar instead?

**Comment by ChiaHuaLu** [comment]
Can consider use the calendar's agenda view

**Comment by rolsanmordua** [comment]
This looks interesting: https://fullcalendar.io/docs/google-calendar @alex-bellon

**Comment by ChiaHuaLu** [comment]
Will use Google Calendar's Agenda view on the homepage under the Upcoming Events label, to be sized in the same way as the facebook iframes
